import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs"
import "./globals.css";
import {Navigation} from "./components/navigation"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased`}>
          <header className="bg-slate-900 text-white p-4 text-center">
            <Navigation />
          </header>
          {children}
          <footer className="bg-slate-900 text-white p-4 text-center">
            codevolution
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}

